name = "copofit"
version = "0.1.0"
license = "MIT"
author = "HugoMVale"
maintainer = "57530119+HugoMVale@users.noreply.github.com"
copyright = "Copyright 2024, HugoMVale"
homepage = "https://github.com/HugoMVale/copofit"
keywords = ["kinetics", "copolymerization", "fit"]

[build]
auto-executables = false
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]
# stdlib = { git = "https://github.com/fortran-lang/stdlib", branch = "stdlib-fpm" }
odrpack = { git = "https://github.com/HugoMVale/odrpack95", branch = "main" }
# odepack = { git = "https://github.com/Nicholaswogan/odepack", branch = "main" }
